### ISSUE TITLE
Few questions related with the propagation algorithm

### ISSUE THREAD

**Issue by erickericki** [jpbos/WavePy#13]
Hello, my name is Erick Nunez I am a physics student at the Industrial University of Santander (Colombia). I am currently doing my major project for Bsc. degree, studying the influence of the number of phase screens on a propagated Gaussian beam. That’s why I am using your wonderful library/software (Wavepy). Therefore, I would like to kindly ask you some questions related with the propagation algorithm you already implement.

Here there are some results i have obtained so far:

![image](https://user-images.githubusercontent.com/88429222/143960954-5a62c9d4-6e40-4c05-aef5-93e2f1286aaf.png)

QUESTIONS

**1. The Phase screens are not always equidistant, I ran a simulation with the following data** 

![image](https://user-images.githubusercontent.com/88429222/143961009-e1e15c57-8e38-48b9-a555-1f4cfb9ccfa5.png)

**And I obtained these positions:**

![image](https://user-images.githubusercontent.com/88429222/143961080-c9e90f0b-67c7-4ac9-9ebe-59f5c0fbb21a.png)

**With respect to the distance per screen, no equidistant positions are obtained. Are the screens fixed to be equidistant?**

**2. Could you please explain if the scintillation index is restricted to the points contained in the pupil? Did you consider if there is some influence on the scintillation index when you are restricted to the pupil? Why not evaluate the result in the whole output?**

![image](https://user-images.githubusercontent.com/88429222/143961432-56ab5bfe-bf1f-4e19-b151-b6f92ffd98a8.png)

**3. Could you clarify if the beam defined in the simulations is really collimated? Since after verifying the evolution of the intensity distribution with the distance it seems not to be.**

![image](https://user-images.githubusercontent.com/88429222/143961483-c05746e7-c60a-43ab-b11a-57823407155c.png)

500 m Propagation Distance
![image](https://user-images.githubusercontent.com/88429222/143961538-88c0f7d8-271f-4222-bf94-13a4d72dd25d.png)

50000 m Propagation distance:
![image](https://user-images.githubusercontent.com/88429222/143961552-e4fec9c4-117b-495e-8c99-28fd42dd1f04.png)

I will really appreciate you help and comments.
Thanks in advanced
Have a nice day!

Beck, J., Bekins, C., & Bos, J. P. (2016, May). WavePy: A Python package for wave optics. In SPIE Defense+ Security (pp. 984603-984603). International Society for Optics and Photonics.

**Comment by jpbos** [comment]
Erick: thanks for taking advantage of WavePy. I'll try and answer your questions briefly here. If you have follow ups please email me directly jpbos at Mtu dot edu. 

1) There is a thought (I don't have the references handy) that placing the first and last phase screens half of the inter-screen spacing distance will produce a better result. There is some solid reasoning here. If you are looking to replicate accurate scintillation or differential tilt in an image the effect of the phase screen at the source or receiver can be zero (see works by Jack E. McCrae, Santasri R. Bose-Pillai and others for more detail). 

2)In a Wave Optics Simulation (WOS) only the statistics inside the guard band are guaranteed to be accurate. The closer you get to the edges the more likely you are to encounter wrap-around ringing effects. Also, this simulation model started as a program to analyze partially coherent collimated Gaussian beams. (There's still some code included to that effect.) In that case, analyzing scintillation outside of the predicted beam size (with turbulence effects) is unlikely to produce accurate results (it's an SNR issue).

3) Collimated in this case means a uniform phase front. The beam will still expand because of diffraction. Also, if you are not using the correct sampling there could be additional beam expansion. I don't know that I have double checked that the predicted beam radius matched prediction but it's one of those things that has been done so many times by so many people you take it for granted. Especially at 50 km I would expect the beam size to be relatively large if the original beamwaist was small.

**Comment by erickericki** [comment]
Thank you very much for your help and your time, I have clarified a lot about the operation of the library, in addition to solving several doubts I had. Thanks and have a nice day.
